#INITIAL SETTINGS
max_trials: 10
input_width: 168
train_ratio: 0.9
epochs: 10
features: [ "20"]  # Features to use for training
prediction_feature: "20"  # Feature to use for prediction
optimizer: "adam"
metrics: [ 'mse', 'mae' ]