#INITIAL SETTINGS:
num_hidden_layer: [ 512, 128, 64]
input_width: 168
output_length: 1 # predict 1 hour
train_ratio: 0.9
epochs: 15
batch_size: 512
features: [ "Amount of Consumption"]  # Features to use for training
prediction_feature: "Amount of Consumption"  # Feature to use for prediction
optimizer: "adam"
loss: "mse"
metrics: [ 'mse', 'mae' ]