#INITIAL SETTINGS
num_hidden_layer: [ 50, 130 , 100 ]
input_width: 168
output_length: 1 # predict 1 hour
train_ratio: 0.9
epochs: 10
batch_size: 512
features: ['Global_active_power']  # Features to use for training
prediction_feature: 'Global_active_power'
optimizer: "adam"
metrics: [ 'mse', 'mae' ]