#INITIAL SETTINGS
kernel_size: 12
nb_filters: 64  # Số lượng filter trong mỗi kernal mask
list_dilation: [1, 2]
input_width: 168
output_length: 1 # predict 1 hour
train_ratio: 0.9
num_features: 1
features: ['temperatures', "humidity", "pressure", "energy"]  # Features to use for training
optimizer: "adam"
metrics: [ 'mse', 'mae' ]