#INITIAL SETTINGS:
num_hidden_layer: [ 10, 100, 200]
input_width: 168
output_length: 1 # predict 1 hour
train_ratio: 0.9
epochs: 15
batch_size: 512
features: [ "temperatures", "humidity", "pressure","energy" ]  # Features to use for training
prediction_feature: "energy"  # Feature to use for prediction
optimizer: "adam"
metrics: [ 'mse', 'mae' ]