#INITIAL SETTINGS: FOR LSTM and TCN
kernel_size: 12
nb_filters: 64  # Số lượng filter trong mỗi kernal mask
list_dilation: [ 1, 2 ]
num_hidden_layer: [ 50, 100 , 100]
input_width: 168
output_length: 1 # predict 1 hour
train_ratio: 0.9
epochs: 50
batch_size: 512
features: [ "temperatures", "humidity", "pressure","energy" ]  # Features to use for training
num_features: 4  # Number of features
prediction_feature: "energy"  # Feature to use for prediction
optimizer: "adam"
metrics: [ 'mse', 'mae' ]