#INITIAL SETTINGS
num_hidden_layer: [ 50, 130 , 100 ]
input_width: 168
output_length: 1 # predict 1 hour
train_ratio: 0.9
epochs: 50
batch_size: 128
features: [ "Amount of Consumption", "Temperature" ]  # Features to use for training
prediction_feature: "Amount of Consumption"  # Feature to use for prediction
optimizer: "adam"
metrics: [ 'mse', 'mae' ]